---
title: "Untitled"
author: "Mick Adriaansens"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_packages}
library(ggplot2)
library(tidyr)
library(dplyr)
```

```{r load_Archaea}
Models <- read.delim('/nesi/nobackup/uc04105/All_models_likelihood.tsv', sep='\t', stringsAsFactors = TRUE)
```

```{r}
Splot <- ggplot(Models[Models$set=='Seed',], aes(y=likelihood, x=model, fill=model)) + geom_boxplot(outlier.alpha = 0) + geom_jitter(alpha=0.3) + ggtitle('Best models and their score from Seed') + theme(axis.title.y = element_text(color = "black", size = 15, angle = 0, hjust = .5, vjust = .5, face = "bold"),
                                                                                                                                                                axis.title.x = element_text(color = "black", size = 15, angle = 0, hjust = .5, vjust = .5, face = "bold")) +  theme(plot.title = element_text(size = 10, face = "bold")) + ylim(-72500, -50000)


Eplot <- ggplot(Models[Models$set=='Euk',], aes(y=likelihood, x=model, fill=model)) + geom_boxplot(outlier.alpha = 0)+ geom_jitter(alpha=0.3) + ggtitle('Best models and their score from Euk') + theme(axis.title.y = element_text(color = "black", size = 15, angle = 0, hjust = .5, vjust = .5, face = "bold"),
                                                                                                                                                                axis.title.x = element_text(color = "black", size = 15, angle = 0, hjust = .5, vjust = .5, face = "bold")) +  theme(plot.title = element_text(size = 10, face = "bold")) + ylim(-72500, -50000)

Aplot <- ggplot(Models[Models$set=='Arc',], aes(y=likelihood, x=model, fill=model)) + geom_boxplot(outlier.alpha = 0)+ geom_jitter(alpha=0.3) + ggtitle('Best models and their score from Arc') + theme(axis.title.y = element_text(color = "black", size = 15, angle = 0, hjust = .5, vjust = .5, face = "bold"),
                                                                                                                                                                axis.title.x = element_text(color = "black", size = 15, angle = 0, hjust = .5, vjust = .5, face = "bold")) +  theme(plot.title = element_text(size = 10, face = "bold")) + ylim(-72500, -50000)

Bplot <- ggplot(Models[Models$set=='Bac',], aes(y=likelihood, x=model, fill=model)) + geom_boxplot(outlier.alpha = 0)+ geom_jitter(alpha=0.3) + ggtitle('Best models and their score from Bac') + theme(axis.title.y = element_text(color = "black", size = 15, angle = 0, hjust = .5, vjust = .5, face = "bold"),
                                                                                                                                                                axis.title.x = element_text(color = "black", size = 15, angle = 0, hjust = .5, vjust = .5, face = "bold")) +  theme(plot.title = element_text(size = 10, face = "bold")) + ylim(-72500, -50000)
```

```{r}
library(gridExtra)
BF<-grid.arrange(Splot, Eplot, Aplot, Bplot, nrow = 1)
BF
```
