mkdir ~/GTDB_226
mkdir ~/GTDB_226/Bac_DB
mkdir ~/GTDB_226/Bac_DB/tsv
mkdir ~/GTDB_226/Bac_DB/fasta
mkdir ~/GTDB_226/ArcDB
mkdir ~/HMM
mkdir ~/HMM/PF00999
mkdir ~/results/MMseqs/
mkdir ~/results/MMseqs/Eukarya
mkdir ~/results/MMseqs/Bacteria
mkdir ~/results/MMseqs/Archaea
mkdir ~/results/MMseqs/Eukarya/part2
mkdir ~/results/MMseqs/Bacteria/part2
mkdir ~/results/MMseqs/Archaea/part2
mkdir ~/results/MMseqs/Eukarya/part3
mkdir ~/results/MMseqs/Bacteria/part3
mkdir ~/results/MMseqs/Archaea/part3
mkdir ~/results/MMseqs/PF00999
mkdir ~/results/HMMsearch/
mkdir ~/results/HMMsearch/PF00999
mkdir ~/results/HMMsearch/Archaea
mkdir ~/results/HMMsearch/Bacteria
mkdir ~/results/HMMsearch/Eukarya
mkdir ~/results/HMMscan/
mkdir ~/results/HMMscan/Archaea
mkdir ~/results/HMMscan/Eukarya
mkdir ~/results/HMMscan/Bacteria

mkdir ~/results/HMMalign/
mkdir ~/results/HMMalign/Eukarya
mkdir ~/results/HMMalign/Eukarya/PF00999/part3
mkdir ~/results/HMMalign/Eukarya/PF03600
mkdir ~/results/HMMalign/Eukarya/PF03553
mkdir ~/results/HMMalign/Eukarya/PF06450
mkdir ~/results/HMMalign/Archaea
mkdir ~/results/HMMalign/Archaea/PF00999/part3
mkdir ~/results/HMMalign/Archaea/PF03600
mkdir ~/results/HMMalign/Archaea/PF03553
mkdir ~/results/HMMalign/Archaea/PF06450

mkdir ~/results/HMMalign/Bacteria
mkdir ~/results/HMMalign/Bacteria/PF00999
mkdir ~/results/HMMalign/Bacteria/PF00999/part3
mkdir ~/results/HMMalign/Bacteria/PF03600
mkdir ~/results/HMMalign/Bacteria/PF03553
mkdir ~/results/HMMalign/Bacteria/PF06450

mkdir ~/tree_input
mkdir ~/RED
mkdir ~/tree_input/fl
mkdir ~/results/HMMalign/PF00999

mkdir ~/chloroplast_mitochondria_genomes
mkdir ~/chloroplast_mitochondria_genomes/database
mkdir ~/chloroplast_mitochondria_genomes/blastn_output
mkdir ~/chloroplast_mitochondria_genomes/euk_cpa_seeds
